version: "3.9"

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: prism_apex_api
    environment:
      - NODE_ENV=production
      - PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  dashboard:
    build:
      context: ./apps/dashboard
      dockerfile: Dockerfile
    container_name: prism_apex_dashboard
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
