
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: prism-api:latest
    container_name: prism-api
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-8000}
    ports:
      - "8000:${PORT:-8000}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:${PORT:-8000}/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
