version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: prism-apex-api:local
    container_name: prism-apex-api
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 8080
      DATA_DIR: /var/lib/prism-apex-tool
    volumes:
      - prism_data:/var/lib/prism-apex-tool
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 15s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    image: prism-apex-dashboard:local
    container_name: prism-apex-dashboard
    depends_on:
      api:
        condition: service_healthy
    environment:
      # The SPA will call /api/* — nginx will proxy to api:8080
      # If you host behind a domain, update nginx.conf accordingly.
      NODE_ENV: production
    ports:
      - "5173:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 15s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  prism_data:
