name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/prism-apex-tool
            git pull origin main
            docker-compose build
            docker-compose up -d

      - name: Notify Slack on Deployment Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Prism Apex Tool deployed successfully"}' \
            ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify Slack on Deployment Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ Prism Apex Tool deployment failed"}' \
            ${{ secrets.SLACK_WEBHOOK }}
