-- Tickets generated by strategies (DB-only; no files)
CREATE TABLE IF NOT EXISTS tickets (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol          TEXT NOT NULL,
  strategy        TEXT NOT NULL,
  direction       TEXT NOT NULL CHECK (direction IN ('LONG','SHORT')),
  session_date_utc DATE NOT NULL,
  opened_at_utc   TIMESTAMPTZ NOT NULL,
  closed_at_utc   TIMESTAMPTZ NOT NULL,
  entry_price     DOUBLE PRECISION NOT NULL,
  exit_price      DOUBLE PRECISION NOT NULL,
  stop_price      DOUBLE PRECISION,
  target_price    DOUBLE PRECISION,
  pnl             DOUBLE PRECISION,
  meta            JSONB DEFAULT '{}'::jsonb,
  created_at_utc  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tickets_dedupe
  ON tickets(symbol, strategy, direction, opened_at_utc);
CREATE INDEX IF NOT EXISTS ix_tickets_session ON tickets(session_date_utc);
CREATE INDEX IF NOT EXISTS ix_tickets_symbol ON tickets(symbol);
