name: CI

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run calibration sweeps
        run: make calibrate

      - name: Lint Python
        run: flake8 .

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Lint frontend
        run: cd frontend && npm install && npm run lint

      - name: Build API image
        run: docker build -f Dockerfile.api -t prism-apex-api:ci .

      - name: Build frontend image
        run: docker build -f Dockerfile.frontend -t prism-apex-frontend:ci .

      - name: Run Python tests
        run: pytest
